version: 2

build:
  commands:
    - echo "Building Orbix Market..."
    - php --version

services:
  - type: web
    name: orbix-market
    env: php
    plan: free
    buildCommand: echo "No build required for PHP"
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: orbix-db
    plan: free
